from __future__ import annotations
import json, subprocess, sys, time, uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).resolve().parents[1] / "data" / "project_workspaces"

def now() -> str: return datetime.now(timezone.utc).isoformat()

def infer_profile(project: dict[str, Any]) -> str:
    text = " ".join(map(str, [project.get("original_idea", ""), project.get("analysis", {}), project.get("solution", {}), project.get("architecture", {})])).lower()
    if any(x in text for x in ["computer vision", "image", "plant disease", "object detection", "classification"]): return "computer_vision"
    if any(x in text for x in ["iot", "sensor", "smart agriculture", "hydroponic", "temperature", "humidity"]): return "iot"
    if any(x in text for x in ["nlp", "language model", "text classification"]): return "nlp"
    return "general_ai"

def build_workspace(project: dict[str, Any]) -> dict[str, Any]:
    project_id = str(project["project_id"]); root = BASE_DIR / project_id; root.mkdir(parents=True, exist_ok=True)
    profile = infer_profile(project)
    files = {
      "README.md": f"# {project.get('project_name','AURA Project')}\n\nGenerated by AURA Build & Execution Core.\n\nIdea: {project.get('original_idea','')}\nProfile: {profile}\n\nScientific claims are never fabricated. Training/evaluation require approved data and an approved runtime.\n",
      "aura_project.json": json.dumps(project, indent=2, ensure_ascii=False),
      "requirements.txt": "ultralytics>=8.3.0\npyyaml>=6.0\n",
      "src/__init__.py": "",
      "src/config.py": f"PROJECT_ID = {project_id!r}\nPROFILE = {profile!r}\n",
      "src/pipeline.py": "def run_pipeline(input_value):\n    return {'input': input_value, 'status': 'scaffold_ready'}\n",
      "tests/__init__.py": "",
      "tests/test_pipeline.py": "from src.pipeline import run_pipeline\n\ndef test_pipeline_smoke():\n    assert run_pipeline('AURA_SMOKE_INPUT')['status'] == 'scaffold_ready'\n",
      "scripts/smoke_test.py": "import json, sys\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))\nfrom src.pipeline import run_pipeline\nprint(json.dumps({'passed':True,'result':run_pipeline('AURA_SMOKE_INPUT')}))\n",
      "scripts/dataset_prepare.py": '''from pathlib import Path\nimport json, sys\nROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)\nconfig=DATA/'dataset.yaml'\nimages=[p for p in DATA.rglob('*') if p.suffix.lower() in {'.jpg','.jpeg','.png','.bmp','.webp'}]\nresult={'status':'READY' if config.exists() else 'BLOCKED','dataset_yaml':str(config),'image_files_found':len(images),'approved_dataset':config.exists(),'scientific_result':False}\nif not config.exists(): result['reason']='Place an approved YOLO dataset configuration at data/dataset.yaml. AURA will not invent a dataset.'\n(ART/'dataset_status.json').write_text(json.dumps(result,indent=2),encoding='utf-8'); print(json.dumps(result,indent=2)); sys.exit(0 if config.exists() else 2)\n''',
      "scripts/train_model.py": '''from pathlib import Path\nimport json, sys\nROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'/'dataset.yaml'; MODEL=ROOT/'models'/'base.pt'; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)\nif not DATA.exists(): result={'status':'BLOCKED','trained':False,'reason':'Approved data/dataset.yaml is required.','scientific_result':False}; (ART/'training_status.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(2)\ntry: from ultralytics import YOLO\nexcept Exception as exc: result={'status':'BLOCKED','trained':False,'reason':'Ultralytics is not installed in the approved environment.','error':str(exc),'scientific_result':False}; (ART/'training_status.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(2)\nif not MODEL.exists(): result={'status':'BLOCKED','trained':False,'reason':'Approved base weights are required at models/base.pt.','scientific_result':False}; (ART/'training_status.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(2)\ntry:\n model=YOLO(str(MODEL)); run=model.train(data=str(DATA),epochs=10,imgsz=640,project=str(ART),name='aura_plant_disease',exist_ok=True); result={'status':'EXECUTED','trained':True,'run':str(getattr(run,'save_dir','')),'scientific_result':False,'review_required':True}\nexcept Exception as exc: result={'status':'FAILED','trained':False,'reason':'Training failed.','error':str(exc),'scientific_result':False}\n(ART/'training_status.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(0 if result['status']=='EXECUTED' else 2)\n''',
      "scripts/evaluate_model.py": '''from pathlib import Path\nimport json, sys\nROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'/'dataset.yaml'; WEIGHTS=ROOT/'artifacts'/'aura_plant_disease'/'weights'/'best.pt'; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)\nif not DATA.exists() or not WEIGHTS.exists(): result={'status':'BLOCKED','metrics_available':False,'metrics':{},'reason':'Evaluation requires dataset.yaml and executed best.pt weights.','scientific_result':False}; (ART/'evaluation.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(2)\ntry:\n from ultralytics import YOLO\n model=YOLO(str(WEIGHTS)); m=model.val(data=str(DATA),split='test'); result={'status':'EXECUTED','metrics_available':True,'metrics':{'map50':float(m.box.map50),'map50_95':float(m.box.map),'precision':float(m.box.mp),'recall':float(m.box.mr)},'scientific_result':True,'review_required':True}\nexcept Exception as exc: result={'status':'FAILED','metrics_available':False,'metrics':{},'reason':'Evaluation failed.','error':str(exc),'scientific_result':False}\n(ART/'evaluation.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(0 if result['status']=='EXECUTED' else 2)\n''',
      "scripts/baseline_evaluate.py": '''from pathlib import Path
import json, sys
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'data'/'dataset.yaml'; WEIGHTS=ROOT/'models'/'baseline.pt'; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
if not DATA.exists() or not WEIGHTS.exists():
 result={'status':'BLOCKED','metrics_available':False,'metrics':{},'reason':'Baseline evaluation requires approved data/dataset.yaml and models/baseline.pt. AURA will not invent a baseline.','scientific_result':False}
else:
 try:
  from ultralytics import YOLO
  model=YOLO(str(WEIGHTS)); m=model.val(data=str(DATA),split='test')
  result={'status':'EXECUTED','metrics_available':True,'metrics':{'map50':float(m.box.map50),'map50_95':float(m.box.map),'precision':float(m.box.mp),'recall':float(m.box.mr)},'scientific_result':True,'review_required':True}
 except Exception as exc:
  result={'status':'FAILED','metrics_available':False,'metrics':{},'reason':'Baseline evaluation failed.','error':str(exc),'scientific_result':False}
(ART/'baseline_evaluation.json').write_text(json.dumps(result,indent=2)); print(json.dumps(result,indent=2)); sys.exit(0 if result['status']=='EXECUTED' else 2)
''',
      "scripts/experiment_runner.py": '''import json, subprocess, sys\nfrom pathlib import Path\nROOT=Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)\nrecords=[]\nfor name in ['dataset_prepare.py','baseline_evaluate.py','train_model.py','evaluate_model.py']:\n p=subprocess.run([sys.executable,str(ROOT/'scripts'/name)],cwd=ROOT,capture_output=True,text=True,shell=False); records.append({'task':name,'exit_code':p.returncode,'stdout':p.stdout[-8000:],'stderr':p.stderr[-8000:]})\n if p.returncode: break\nresult={'status':'EXECUTED' if records and all(x['exit_code']==0 for x in records) else 'BLOCKED_OR_FAILED','steps':records,'scientific_validation':False,'review_required':True}\n(ART/'experiment_run.json').write_text(json.dumps(result,indent=2),encoding='utf-8'); print(json.dumps(result,indent=2)); sys.exit(0 if result['status']=='EXECUTED' else 2)\n''',
      "execution_manifest.json": json.dumps({"allowed_tasks":["smoke_test","dataset_prepare","train_model","evaluate_model","baseline_evaluate","experiment_run"],"shell":False,"timeout_seconds":300},indent=2)
    }
    if profile == 'computer_vision':
        files['src/vision.py'] = "def predict_image(image_path):\n    raise RuntimeError('No trained model available. Run approved training first.')\n"
        files['data/README.md'] = "Place an approved YOLO dataset.yaml here and ensure its referenced image/label paths are accessible.\n"
        files['models/README.md'] = "Place approved proposed weights at models/base.pt. Optional approved baseline weights may be placed at models/baseline.pt. AURA never invents a baseline.\n"
    elif profile == 'iot': files['data/README.md'] = 'Place approved sensor data here.\n'
    else: files['data/README.md'] = 'Place approved project data here.\n'
    created=[]
    for rel,content in files.items():
        path=root/rel; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding='utf-8'); created.append(rel)
    return {'workspace':str(root),'profile':profile,'files':created,'status':'generated'}

def _artifact_manifest(root: Path):
    ar=root/'artifacts'; return [{'path':str(p.relative_to(root)),'size':p.stat().st_size} for p in ar.rglob('*') if p.is_file()] if ar.exists() else []

def _read_result_summary(root: Path) -> dict[str, Any]:
    summary: dict[str, Any] = {}
    art = root / "artifacts"
    for name in ("dataset_status.json", "training_status.json", "baseline_evaluation.json", "evaluation.json", "experiment_run.json", "results_summary.json"):
        path = art / name
        if path.exists():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                summary[name] = data
            except Exception:
                summary[name] = {"status": "UNREADABLE"}
    return summary


def execute(project_id: str, task: str, timeout: int=120):
    root=BASE_DIR/project_id
    if not root.exists() or not (root/'execution_manifest.json').exists(): return {'status':'BLOCKED','message':'Build workspace has not been generated.'}
    commands={'smoke_test':'smoke_test.py','dataset_prepare':'dataset_prepare.py','train_model':'train_model.py','evaluate_model':'evaluate_model.py','baseline_evaluate':'baseline_evaluate.py','experiment_run':'experiment_runner.py'}
    if task not in commands: return {'status':'BLOCKED','message':'Task is not allowlisted.'}
    execution_id='exec-'+uuid.uuid4().hex[:12]; started=now(); t=time.perf_counter(); cmd=[sys.executable,str(root/'scripts'/commands[task])]
    try:
        proc=subprocess.run(cmd,cwd=root,capture_output=True,text=True,timeout=min(max(timeout,1),300),shell=False); status='EXECUTED' if proc.returncode==0 else ('BLOCKED' if task in {'dataset_prepare','baseline_evaluate','train_model','evaluate_model','experiment_run'} and 'BLOCKED' in (proc.stdout or '') else 'FAILED'); stdout,stderr,exit_code=proc.stdout,proc.stderr,proc.returncode; error=None
    except subprocess.TimeoutExpired as exc: status='TIMEOUT'; stdout=exc.stdout or ''; stderr=exc.stderr or ''; exit_code=None; error=f'Execution exceeded {timeout} seconds.'
    except Exception as exc: status='FAILED'; stdout=''; stderr=str(exc); exit_code=None; error=str(exc)
    record={'execution_id':execution_id,'project_id':project_id,'task':task,'status':status,'started_at':started,'finished_at':now(),'duration_seconds':round(time.perf_counter()-t,3),'command':cmd,'cwd':str(root),'timeout_seconds':timeout,'exit_code':exit_code,'stdout':stdout[-12000:],'stderr':stderr[-12000:],'error':error,'artifacts':_artifact_manifest(root),'scientific_validation':False,'review_required':True,'result_summary':_read_result_summary(root)}
    d=root/'executions'; d.mkdir(exist_ok=True); (d/f'{execution_id}.json').write_text(json.dumps(record,indent=2),encoding='utf-8')
    try:
        from services.results_engine import persist_results
        record['results_summary'] = persist_results({'project_id': project_id}, root)
        (d/f'{execution_id}.json').write_text(json.dumps(record,indent=2),encoding='utf-8')
    except Exception as exc:
        record['results_ingest_error'] = str(exc)
    return record

def list_executions(project_id: str):
    root=BASE_DIR/project_id/'executions'
    if not root.exists(): return []
    out=[]
    for p in sorted(root.glob('exec-*.json'),reverse=True):
        try: out.append(json.loads(p.read_text(encoding='utf-8')))
        except Exception: pass
    return out
